QA_gen/QA_gen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('generator.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

QA_gen/generator/urls.py
from django.urls import path
from generator import views

app_name = 'generator'
urlpatterns = [
    path('', views.doc_register, name='doc_register'),   # 登録ページ
    path('result/', views.ResultList.as_view(), name='gen_result'),   # QA生成結果ページ
    path('del/<int:qac_idx>/', views.qac_del, name='qac_del'),   # QAの削除
    path('docs/', views.DocList.as_view(), name='doc_list'),     # ドキュメント一覧
    path('docs/qa/<int:doc_id>', views.doc_qa_list, name='doc_qa_list'),     # ドキュメント毎のQA一覧
]

QA_gen/generator/models.py
from django.db import models
from django.conf import settings
import os


def delete_previous_file(function):
    def wrapper(*args, **kwargs):
        self = args[0]

        result = Document.objects.filter(pk=self.pk)
        previous = result[0] if len(result) else None
        super(Document, self).save()

        result = function(*args, **kwargs)

        if previous:
            os.remove(settings.MEDIA_ROOT + '/' + previous.document.name)
        return result
    return wrapper


class Document(models.Model):
    @delete_previous_file
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super(Document, self).save()

    @delete_previous_file
    def delete(self, using=None, keep_parents=False):
        super(Document, self).delete()

    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)


class Context(models.Model):
    context = models.CharField('ドキュメント', max_length=1024)

    def __str__(self):
        return self.context


class QAC(models.Model):
    idx = models.IntegerField('ID', blank=True, default=0)
    question = models.CharField('質問文', max_length=1024)
    answer = models.CharField('回答文', max_length=1024)
    document = models.ForeignKey(Context, verbose_name='ドキュメント', related_name='qacs', on_delete=models.CASCADE, default=0)

    def __str__(self):
        return self.question

QA_gen/generator/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django import forms
from django.views.generic.list import ListView
import pandas as pd

from .models import Document, QAC, Context
from .vae import generator



class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('document', )


# Create your views here.
def doc_register(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            docs = Document.objects.all()
            for doc in docs:
                doc.delete()
            form.save()

            target = 'media/' + Document.objects.all()[0].document.name
            model = 'media/model/best_f1_model.pt'
            save = 'media/documents/result.csv'
            results = generator.QA_generation(target, model, save)
            qacs = QAC.objects.all()
            for qac in qacs:
                qac.delete()
            ctxs = Context.objects.all()
            for ctx in ctxs:
                ctx.delete()
            for idx, res in enumerate(results):
                qac = QAC()
                qac.idx = idx
                qac.question = res['question']
                qac.answer = res['answer']
                new_ctx = True
                if idx > 1:
                    ctxs = Context.objects.all()
                    for ctx in ctxs:
                        if ctx.context == res['context']:
                            qac.document = ctx
                            new_ctx = False
                if new_ctx:
                    ctx = Context()
                    ctx.context = res['context']
                    ctx.save()
                qac.document = ctx
                qac.save()


            return redirect('generator:gen_result')
    else:
        form = DocumentForm()
    return render(request, 'generator/doc_register.html', {
        'form': form
    })


class DocList(ListView):
    context_object_name = 'docs'
    template_name = 'generator/doc_list.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.object_list = Context.objects.all()
        context = self.get_context_data(object_list=self.object_list)
        return self.render_to_response(context)


def doc_qa_list(request, doc_id):
    doc = get_object_or_404(Context, pk=doc_id)
    qacs = doc.qacs.all().order_by('id')
    return render(request, 'generator/doc_qa_list.html', {'qacs': qacs, 'doc': doc})


class ResultList(ListView):
    context_object_name = 'qacs'
    template_name = 'generator/result.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.object_list = QAC.objects.all()
        context = self.get_context_data(object_list=self.object_list)
        return self.render_to_response(context)


def qac_del(request, qac_idx):
    qacs = QAC.objects.all()
    dics = []
    local_idx = 0
    for qac in qacs:
        if qac.idx == qac_idx:
            qac.delete()
        else:
            qac.idx = local_idx
            qac.save()
            local_idx += 1
            dic = {}
            # dic['context'] = qac.document.context
            dic['answer'] = qac.answer
            dic['question'] = qac.question
            dics.append(dic)
    # csvを更新
    save = 'media/documents/result.csv'
    df = pd.DataFrame(dics, columns=['question', 'answer'])
    df.to_csv(save, encoding='cp932')

    return redirect('generator:gen_result')

QA_gen/generator/templates/generator/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'generator/css/bootstrap.min.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}My books{% endblock %}</title>
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
<script src="{% static 'generator/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'generator/js/bootstrap.bundle.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

QA_gen/generator/templates/generator/doc_list.html
{% extends "generator/base.html" %}

{% block title %}QAジェネレータ{% endblock title %}

{% block content %}
    <h3 class="mt-4 border-bottom">QA生成支援ツール</h3>
    <h4 class="mt-4 border-bottom">生成結果（ドキュメント一覧）</h4>

    <p><a href="{% url 'generator:gen_result' %}" class="btn btn-primary"> QA一覧 </a></p>

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ドキュメント</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for doc in docs %}
        <tr>
          <td>{{ doc.context }}</td>
          <td>
            <a href="{% url 'generator:doc_qa_list' doc_id=doc.id %}" class="btn btn-outline-info btn-sm">QAを表示</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
        {% endif %}
        {% for linkpage in page_obj.paginator.page_range %}
          {% ifequal linkpage page_obj.number %}
            <li class="page-item active"><a class="page-link" href="#">{{ linkpage }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
{% endblock content %}

QA_gen/generator/templates/generator/doc_qa_list.html
{% extends "generator/base.html" %}

{% block title %}QAジェネレータ{% endblock title %}

{% block content %}
    <h3 class="mt-4 border-bottom">QA生成支援ツール</h3>
    <h4 class="mt-4 border-bottom">ドキュメントQA</h4>

    <p><a href="{% url 'generator:doc_list' %}" class="btn btn-primary"> ドキュメント確認 </a></p>
    <p><a href="{% url 'generator:gen_result' %}" class="btn btn-primary"> QA一覧 </a></p>

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ドキュメント</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{ doc.context|linebreaksbr }}</td>
        </tr>
      </tbody>
    </table>

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>質問</th>
          <th>回答</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for qac in qacs %}
        <tr>
          <td>{{ qac.idx }}</td>
          <td>{{ qac.question|linebreaksbr }}</td>
          <td>{{ qac.answer|linebreaksbr }}</td>
          <td>
            <a href="" class="btn btn-outline-danger btn-sm">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}

QA_gen/generator/templates/generator/doc_register.html
{% extends "generator/base.html" %}

{% block title %}QAジェネレータ{% endblock title %}

{% block content %}
    <h3 class="mt-4 border-bottom">QA生成支援ツール</h3>
    <h4 class="mt-4 border-bottom">ドキュメントを選択してください</h4>
    <form action="{% url 'generator:doc_register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">QAを生成</button>
    </form>
{% endblock content %}

QA_gen/generator/templates/generator/result.html
{% extends "generator/base.html" %}

{% block title %}QAジェネレータ{% endblock title %}

{% block content %}
    <h3 class="mt-4 border-bottom">QA生成支援ツール</h3>
    <h4 class="mt-4 border-bottom">QA生成結果</h4>
    <a href="../media/documents/result.csv" download="result.csv"> CSVダウンロード </a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>質問</th>
          <th>回答</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for qac in qacs %}
        <tr>
          <td>{{ qac.idx }}</td>
          <td>{{ qac.question|linebreaksbr }}</td>
          <td>
            {{ qac.answer|linebreaksbr }}
          </td>
          <td>
            <a href="{% url 'generator:qac_del' qac_idx=qac.idx %}" class="btn btn-outline-danger btn-sm">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
    <nav aria-label="Page navigation">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span><span class="sr-only">Previous</span></a></li>
        {% endif %}
        {% for linkpage in page_obj.paginator.page_range %}
          {% ifequal linkpage page_obj.number %}
            <li class="page-item active"><a class="page-link" href="#">{{ linkpage }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span><span class="sr-only">Next</span></a></li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
{% endblock content %}

{% block extra_js %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).data("pk"));
     $('#del_url').attr('href', $(this).data("url"));
  });
});
</script>
{% endblock %}